import pygame as pg

# RGB Values
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DARKGREY = (40, 40, 40)
LIGHTGREY = (100, 100, 100)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)

# game settings
WIDTH = 1550
HEIGHT = 775
FPS = 60
TITLE = "hOTLINE ZOMBANI"
BGCOLOR = DARKGREY

TILESIZE = 64
GRIDWIDTH = WIDTH / TILESIZE
GRIDHEIGHT = HEIGHT / TILESIZE

WALL_IMG = "Wall Tile.PNG"
MOUSE_IMG = "Mouse.PNG"

# player settings
PLAYERSPEED = 500
PLAYER_IMG = "manOld_gun.PNG"
PLAYER_HIT_RECT = pg.Rect(0, 0, 35, 35)
PLAYER_HEALTH = 100

# gun settings
BULLET_IMG = "Bullet.PNG"
BULLET_SPEED = 800
BULLET_LIFE = 1000
FIRE_RATE = 300
SPREAD = 20
DAMAGE = 10

# mob settings
MOB_IMG = "zombie_hold.PNG"
SPRINT_IMG = "Sprinter_zombie.PNG"
SHOOTER_IMG = "Shooter_zombie.PNG"
MOB_SPEEDS = [300, 150, 200, 250]
MOB_HIT_RECT = pg.Rect(0, 0, 35, 35)
MOB_HEALTH = 60
MOB_DAMAGE = 10
MOB_KNOCKBACK = 30
AVOID_RADIUS = 50

# Rounds
ROUND_BASE_MOBS = 15
ROUND_MOB_MULTIPLIER = 1.2
MOB_HEALTH_MULTIPLIER = 1.1
SPAWN_INTERVAL = 1000

# misc images
QUIT_BUTTON = "Quit_but.PNG"
BACK_BUTTON = "Back_but.PNG"
CONTINUE_BUTTON = "Continue_but.PNG"
PLAY_BUTTON = "Play_but.PNG"
JUGGERNOG = "Juggernog.PNG"
DOUBLETAP = "DoubleTap.PNG"
MULEKICK = "Mule Kick.PNG"
FIRE_RATE_UP = "Fire Rate.PNG"
DEADSHOT = "Deadshot.PNG"
SPEED_COLA = "Speed Cola.PNG"
MENU_QUIT_BUTTON = "Menu_Quit_but.PNG"
LOGIN_BUTTON = "Log_in_but.PNG"
REGISTER_BUTTON = "Register_but.PNG"
SCORE_BUTTON = "Score_but.PNG"

# prices
JUG_PRICE = 2500
MULE_PRICE = 500
DOUBLE_TAP_PRICE = 1000
SPEED_COLA_PRICE = 500
DEADSHOT_PRICE = 750
FIRE_RATE_PRICE = 1500